name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm un build
  test:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v3
      - run: npm install
      - name: Skip ESLint Config
        run: |
          if [ -f .eslintrc.json ]; then
            echo "ESLint configuration found, running linting..."
          else
            echo "Skipping ESLint configuration..."
          fi
      - run: npm test
        continue-on-error: true
